# Generated by Django 5.1.1 on 2024-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='retail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='price',
            name='wholesale',
            field=models.CharField(max_length=50),
        ),
    ]
